steps:
  # running docker-compose
  - name: 'docker/compose:1.26.2'
    args: ['up', '-d']
    
images:
- 'gcr.io/intelligenceartificielle/classif-service-build'
- 'gcr.io/intelligenceartificielle/docker_classif-server'
