version: '3.3'

services:
  classif-service:
    image: gcr.io/intelligenceartificielle/classif-service-build
    command: ["/home/classif/start-server.sh","8002"]
    volumes:
      - static_volume:/home/classif/demo-classif/bin/demo-web/demo/static
    expose:
      - 8002

  classif-server:
    image: gcr.io/intelligenceartificielle/docker_classif-server
    ports:
      - 8001:80
    volumes:
      - static_volume:/home/classif/demo-classif/bin/demo-web/demo/static
    depends_on:
      - classif-service
      
volumes:
  static_volume:
